language: csharp
mono:
  - latest
dotnet: 1.0.3
sudo: required
dist: trusty
install:
 - dotnet restore
script:
 - dotnet build
 - nuget pack ./AspNetCore.FriendlyExceptions.nuspec -Verbosity detailed
 - nuget push ./AspNetCore.FriendlyExceptions.*.nupkg -Verbosity detailed -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
