language: csharp
mono: none
dotnet: 1.0.3
sudo: required
dist: trusty
install:
 - dotnet restore
script:
 - dotnet pack --configuration release --output nupkgs 
 - dotnet nuget push ./src/nupkgs/AspNetCore.FriendlyExceptions.*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE

